version: "2"
services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: org-blog-backend
    image: melodylane/org-blog:latest
    volumes:
      - ~/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db:5432
  db:
    image: postgres:9.6.13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: docker
