language: clojure
lein: lein
jdk:
  - openjdk8
jobs:
  include:
    - stage: test
      script: docker pull postgres
      script: ./start-test-db.sh
    - stage: build
      script: ./build.sh
    - stage: push-image
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: docker push melodylane/org-blog:latest
services:
  - docker
