:base = http://localhost:3000/api
:post_name = test_post.org

# List all posts
GET :base/posts
User-Agent: Emacs27
Accept-Encoding: compress, gzip

# Add a new post
POST :base/post
Content-Type: application/json
{
"filename": ":post_name",
"post": ":BLOG_METADATA:\n:CATEGORY: Clojure\n:END:\n"
}

# Get by filename
GET :base/post/:post_name
user-agent: emacs27
accept-encoding: compress, gzip

# Get raw post by filename
GET :base/post/:post_name?raw=1
user-agent: emacs27
accept-encoding: compress, gzip

# Remove by filename
DELETE :base/post/:post_name
User-Agent: Emacs27
Accept-Encoding: compress, gzip