:base = http://localhost:3000
:post_name = test_post.org

# List all posts
GET :base/posts
User-Agent: Emacs27
Accept-Encoding: compress, gzip

# Add a new post
POST :base/post?preview=false
Content-Type: application/json
{
"filename": ":post_name",
"path_relative_to_home": "some/path",
"post": ":BLOG_METADATA:\n:CATEGORY: Clojure\n:END:\n",
}

# Get by filename
GET :base/post/:post_name?raw=false
user-agent: emacs27
accept-encoding: compress, gzip

# Get raw post by filename
GET :base/post/:post_name?raw=true
user-agent: emacs27
accept-encoding: compress, gzip

# Remove by filename
DELETE :base/post/:post_name
User-Agent: Emacs27
Accept-Encoding: compress, gzip