#+TITLE: org-blog
#+AUTHOR: Lane Spangler
#+EMAIL: las4vc@virginia.edu

[[https://travis-ci.com/lane-s/org-blog][file:https://travis-ci.com/lane-s/org-blog.svg?branch=master]]

org-blog is intended for emacs users that want to blog directly from org-mode.

org-blog currently does not provide a complete blogging solution right out of the box. It is meant for developers or others who are willing to do the (fairly small) amount of work required to deploy the servers. After this work is done, you'll be able to write and manage posts in emacs. This is great if, like me, you prefer to use emacs for just about everything. For anyone else, it's probably not worth the trouble.

For now, the system consists of three parts:
- The backend (this repo): stores, parses, and serves blog posts.
- [[https://github.com/lane-s/org-blog-mode][org-blog-mode]]: an emacs package that provides an interface for managing posts.
- The frontend: Gets parsed posts from the servers and displays them. An example frontend is on the way.
  
* Deploying org-blog

Pull the docker image

#+BEGIN_SRC bash
docker pull melodylane/org-blog:latest
#+END_SRC

Create a docker-compose.yaml similar to the one included in this project.

Then:

#+BEGIN_SRC bash
docker-compose up
#+END_SRC
    
The sample docker-compose.yaml will run the backend listening on port 3000 and the database on 5432.

* API

See [[./api_examples.http][REST API examples]] to see how the API can be used

* Development

Requires Clojure, [[https://leningen.org/][leiningen]], and Docker

** Dev Database

Pull the postgres docker image
#+BEGIN_SRC bash
docker pull postgres
#+END_SRC

Start the test and dev databases
#+BEGIN_SRC bash
./start-dev-db.sh
#+END_SRC

** Running Tests

#+BEGIN_SRC bash
lein test
#+END_SRC
** Running the development server

#+BEGIN_SRC bash
lein ring server-headless
#+END_SRC

** Build

Creates a standalone jar and a docker image

#+BEGIN_SRC bash
./build.sh
#+END_SRC

Run the standalone jar:
#+BEGIN_SRC bash
java -jar target/org-blog-0.1.0-SNAPSHOT-standalone.jar
#+END_SRC

* License

Copyright © 2019 Lane Spangler

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.

